export const jobType = [
  { value: "fullTime", label: "Full-time" },
  { value: "partTime", label: "Part-time" },
];
export const experienceLevel = [
  { value: "internship", label: "Internship" },
  { value: "entryLevel", label: "Entry level" },
  { value: "midSeniorLevel", label: "Mid-Senior level" },
  { value: "director", label: "Director" },
  { value: "executive", label: "Executive" },
];
export const age = [
  { value: "any", label: "Any" },
  { value: "pastMonth", label: "Past month" },
  { value: "pastWeek", label: "Past week" },
  { value: "past24Hours", label: "Past 24 hours" },
];
export const remote = [
  { value: "onSite", label: "On-site" },
  { value: "hybrid", label: "Hybrid" },
  { value: "remote", label: "Remote" },
];

export const TEST_DATA = [
  {
    title: "Frontend Developer",
    link: "https://lt.linkedin.com/jobs/view/frontend-developer-at-macaw-lithuania-3885133519?position=2&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=tHfjSujJt1deNl0504totw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilniaus, Lithuania",
    companyName: "Macaw Lithuania",
    websiteCreatedAtDateTime: "2024-04-08",
    websiteCreatedAtString: "1 week ago",
    ageInDays: "10",
    keywords: "next js",
    applied: 0,
    blacklisted: 0,
  },
  {
    title: "FuturePros Programme: IT and Software Engineering Track",
    link: "https://lt.linkedin.com/jobs/view/futurepros-programme-it-and-software-engineering-track-at-danske-bank-3895354921?position=8&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=yX1OY%2BrZoqsjhF5vgvUHdw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Danske Bank",
    websiteCreatedAtDateTime: "2024-04-17",
    websiteCreatedAtString: "5 hours ago",
    ageInDays: "1",
    keywords: "bnext js",
    applied: 1,
    blacklisted: 1,
  },
  {
    title: "Full-Stack Developer",
    link: "https://lt.linkedin.com/jobs/view/full-stack-developer-at-w3forge-3893978734?position=7&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=h9s%2FmuFndNYj8YTkqHe7Sg%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "W3Forge",
    websiteCreatedAtDateTime: "2024-04-11",
    websiteCreatedAtString: "6 days ago",
    ageInDays: "7",
    keywords: "anode js",
    applied: 1,
    blacklisted: 0,
  },
  {
    title: "DevOps Engineer",
    link: "https://lt.linkedin.com/jobs/view/devops-engineer-at-telia-3890828716?position=25&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=PP12IKymJABMZf5rQbC8Sg%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Telia",
    websiteCreatedAtDateTime: "2024-04-11",
    websiteCreatedAtString: "6 days ago",
    ageInDays: "7",
    keywords: "next js",
    applied: 0,
    blacklisted: 1,
  },
  {
    title: "DevOps Engineer",
    link: "https://lt.linkedin.com/jobs/view/devops-engineer-at-telia-3892340439?position=24&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=m5YPbvbpxedVPJKJPFmJwQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Telia",
    websiteCreatedAtDateTime: "2024-04-12",
    websiteCreatedAtString: "5 days ago",
    ageInDays: "6",
    keywords: "next js",
    applied: 0,
    blacklisted: 0,
  },
];
