export const TEST_DATA = [
  {
    title: "Front-End Developer (Web team)",
    link: "https://lt.linkedin.com/jobs/view/front-end-developer-web-team-at-surfshark-3815235850?position=1&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=N36ZfAonSTFHm4mkSE4sHw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Surfshark",
    websiteCreatedAtDateTime: "2024-02-01",
    websiteCreatedAtString: "2 months ago",
    ageInDays: 75,
  },
  {
    title: "Frontend Developer",
    link: "https://lt.linkedin.com/jobs/view/frontend-developer-at-macaw-lithuania-3885133519?position=2&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=KHSDQbXPid03Mg%2BYarZKag%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilniaus, Lithuania",
    companyName: "Macaw Lithuania",
    websiteCreatedAtDateTime: "2024-04-08",
    websiteCreatedAtString: "1 week ago",
    ageInDays: 8,
  },
  {
    title: "Fullstack Developer",
    link: "https://lt.linkedin.com/jobs/view/fullstack-developer-at-obdeleven-3871939306?position=3&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=WX2a48k1RMiyHOmZFJz05Q%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Kaunas, Kauno, Lithuania",
    companyName: "OBDeleven",
    websiteCreatedAtDateTime: "2024-03-26",
    websiteCreatedAtString: "2 weeks ago",
    ageInDays: 21,
  },
  {
    title: "Mid-Senior Front-End Engineer (WEB team)",
    link: "https://lt.linkedin.com/jobs/view/mid-senior-front-end-engineer-web-team-at-nord-security-3880681353?position=4&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=s%2BhjDQf%2BFaBvAztpXUNd5g%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Nord Security",
    websiteCreatedAtDateTime: "2024-04-03",
    websiteCreatedAtString: "1 week ago",
    ageInDays: 13,
  },
  {
    title: "Mid-Senior Front-end Engineer",
    link: "https://lt.linkedin.com/jobs/view/mid-senior-front-end-engineer-at-nord-security-3868482388?position=5&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=OWdq8aYFgVYocrBPJFne6Q%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Nord Security",
    websiteCreatedAtDateTime: "2024-03-26",
    websiteCreatedAtString: "2 weeks ago",
    ageInDays: 21,
  },
  {
    title: "Mid-Senior Front-End Engineer (WEB team)",
    link: "https://lt.linkedin.com/jobs/view/mid-senior-front-end-engineer-web-team-at-nord-security-3880679411?position=6&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=SOonpmVCfJ1R5Tts1u%2F6FQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Kaunas, Kauno, Lithuania",
    companyName: "Nord Security",
    websiteCreatedAtDateTime: "2024-04-03",
    websiteCreatedAtString: "1 week ago",
    ageInDays: 13,
  },
  {
    title: "Full-Stack Developer",
    link: "https://lt.linkedin.com/jobs/view/full-stack-developer-at-w3forge-3893978734?position=7&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=JmkgOSN5G9F%2BkbVSFhsUiQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "W3Forge",
    websiteCreatedAtDateTime: "2024-04-11",
    websiteCreatedAtString: "4 days ago",
    ageInDays: 5,
  },
  {
    title: "Senior Frontend Developer",
    link: "https://lt.linkedin.com/jobs/view/senior-frontend-developer-at-coingate-3874348577?position=8&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=zZ2lOKMI5RgL0um3E0aehQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "CoinGate",
    websiteCreatedAtDateTime: "2024-03-29",
    websiteCreatedAtString: "2 weeks ago",
    ageInDays: 18,
  },
  {
    title: "Senior Software Engineer  (Remote or Hybrid)",
    link: "https://lt.linkedin.com/jobs/view/senior-software-engineer-remote-or-hybrid-at-hokodo-3879304038?position=9&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=p68WVUc5xqU1L%2Fx9PyIGXg%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Hokodo",
    websiteCreatedAtDateTime: "2024-04-02",
    websiteCreatedAtString: "1 week ago",
    ageInDays: 14,
  },
  {
    title: "FuturePros Programme: IT and Software Engineering Track",
    link: "https://lt.linkedin.com/jobs/view/futurepros-programme-it-and-software-engineering-track-at-danske-bank-3895354921?position=10&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=JKNPQY3Hxvda0fy7N0p7Pg%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Danske Bank",
    websiteCreatedAtDateTime: "2024-04-12",
    websiteCreatedAtString: "2 days ago",
    ageInDays: 4,
  },
  {
    title: "Javascript Developer",
    link: "https://lt.linkedin.com/jobs/view/javascript-developer-at-ubiquiti-inc-3739270393?position=11&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=LhtJ83%2FXnHT3Fb8gHPFRiQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Kaunas, Kauno, Lithuania",
    companyName: "Ubiquiti Inc.",
    websiteCreatedAtDateTime: "2024-03-14",
    websiteCreatedAtString: "1 month ago",
    ageInDays: 33,
  },
  {
    title: "(Senior) Data Scientists - based in Luxembourg",
    link: "https://lt.linkedin.com/jobs/view/senior-data-scientists-based-in-luxembourg-at-european-investment-bank-eib-3860351600?position=12&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=eWjjnWHQvaS67EtVDzLJUA%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilniaus rajonas, Vilniaus, Lithuania",
    companyName: "European Investment Bank (EIB)",
    websiteCreatedAtDateTime: "2024-03-19",
    websiteCreatedAtString: "3 weeks ago",
    ageInDays: 28,
  },
  {
    title: "FACT Team Offshore Developers",
    link: "https://lt.linkedin.com/jobs/view/fact-team-offshore-developers-at-higher-frog-limited-3890811926?position=13&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=Pm7zEsZS5C7LzdYrdw0WPQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Lithuania",
    companyName: "Higher Frog Limited",
    websiteCreatedAtDateTime: "2024-03-17",
    websiteCreatedAtString: "4 weeks ago",
    ageInDays: 30,
  },
  {
    title: "FACT Team Offshore Developers",
    link: "https://lt.linkedin.com/jobs/view/fact-team-offshore-developers-at-higher-frog-limited-3890814620?position=14&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=%2FfFjxiXfvlrjuPbKwJc%2B1g%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Lithuania",
    companyName: "Higher Frog Limited",
    websiteCreatedAtDateTime: "2024-03-17",
    websiteCreatedAtString: "4 weeks ago",
    ageInDays: 30,
  },
  {
    title: "Middle Full-Stack Developer",
    link: "https://lt.linkedin.com/jobs/view/middle-full-stack-developer-at-exadel-3822888600?position=15&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=VIOHA0YhVCL%2BiGTFILOIlQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Lithuania",
    companyName: "Exadel",
    websiteCreatedAtDateTime: "2024-02-05",
    websiteCreatedAtString: "2 months ago",
    ageInDays: 71,
  },
  {
    title: "FACT Team Offshore Developers",
    link: "https://lt.linkedin.com/jobs/view/fact-team-offshore-developers-at-higher-frog-limited-3890810902?position=16&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=GafsmClMorjSl9U9XAUrYg%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Lithuania",
    companyName: "Higher Frog Limited",
    websiteCreatedAtDateTime: "2024-03-17",
    websiteCreatedAtString: "4 weeks ago",
    ageInDays: 30,
  },
  {
    title: "Software Engineer",
    link: "https://lt.linkedin.com/jobs/view/software-engineer-at-inbank-3874829057?position=17&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=D8tju5v5YRKNw1KJ0gKV5Q%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Inbank",
    websiteCreatedAtDateTime: "2024-03-28",
    websiteCreatedAtString: "2 weeks ago",
    ageInDays: 19,
  },
  {
    title: "FULL STACK .NET DEVELOPER",
    link: "https://lt.linkedin.com/jobs/view/full-stack-net-developer-at-aida-projektai-3862859839?position=18&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=mulHc8jOgSTNHNIO4MWOEQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "AIDA projektai",
    websiteCreatedAtDateTime: "2024-03-19",
    websiteCreatedAtString: "3 weeks ago",
    ageInDays: 28,
  },
  {
    title: "Senior Full-Stack Developer",
    link: "https://lt.linkedin.com/jobs/view/senior-full-stack-developer-at-exadel-3851272608?position=19&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=xP8s6Dq7xOwiEgso2bBVuQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Lithuania",
    companyName: "Exadel",
    websiteCreatedAtDateTime: "2024-03-11",
    websiteCreatedAtString: "1 month ago",
    ageInDays: 36,
  },
  {
    title: "Senior Frontend Web Engineer",
    link: "https://lt.linkedin.com/jobs/view/senior-frontend-web-engineer-at-flo-health-inc-3876782564?position=20&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=PbCjkDEmuAQ3HaL2dkrfZw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Flo Health Inc.",
    websiteCreatedAtDateTime: "2024-03-29",
    websiteCreatedAtString: "2 weeks ago",
    ageInDays: 18,
  },
  {
    title: "Middle/Senior React Front-End Developer (On-Site in Vilnius)",
    link: "https://lt.linkedin.com/jobs/view/middle-senior-react-front-end-developer-on-site-in-vilnius-at-it-gateway-lt-3871221424?position=21&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=sepp5Q%2FwZcVGk1d%2BHUMImg%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "IT Gateway LT",
    websiteCreatedAtDateTime: "2024-03-28",
    websiteCreatedAtString: "2 weeks ago",
    ageInDays: 19,
  },
  {
    title: "Senior Web Developer - Workplace Engineering",
    link: "https://lt.linkedin.com/jobs/view/senior-web-developer-workplace-engineering-at-canonical-3673076613?position=22&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=vOmX7LG4OjhQ1kbnzczM7A%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Canonical",
    websiteCreatedAtDateTime: "2023-06-27",
    websiteCreatedAtString: "9 months ago",
    ageInDays: 294,
  },
  {
    title: "Senior Software Engineer - iTwin Applications",
    link: "https://lt.linkedin.com/jobs/view/senior-software-engineer-itwin-applications-at-bentley-systems-3872070029?position=23&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=HLoeZJ3hHjZMgOI7y7fMFQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Bentley Systems",
    websiteCreatedAtDateTime: "2024-03-27",
    websiteCreatedAtString: "2 weeks ago",
    ageInDays: 20,
  },
  {
    title: "Atlassian Jira & Confluence DevOps Engineer",
    link: "https://lt.linkedin.com/jobs/view/atlassian-jira-confluence-devops-engineer-at-telia-3831257748?position=24&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=R9ZldfuHk1Gb896%2FlbuKuA%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Telia",
    websiteCreatedAtDateTime: "2024-03-14",
    websiteCreatedAtString: "1 month ago",
    ageInDays: 33,
  },
  {
    title: "Senior FrontEnd Developer",
    link: "https://lt.linkedin.com/jobs/view/senior-frontend-developer-at-zedge-3872032670?position=25&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=u0ir70DRaqfYSkGAvSfZRw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "ZEDGE",
    websiteCreatedAtDateTime: "2024-04-02",
    websiteCreatedAtString: "1 week ago",
    ageInDays: 14,
  },
  {
    title: "Full-stack Engineer (AWS, Java)",
    link: "https://lt.linkedin.com/jobs/view/full-stack-engineer-aws-java-at-telia-3860315301?position=26&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=42nJoyFkXYPVvW9CxL3OOw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Telia",
    websiteCreatedAtDateTime: "2024-03-19",
    websiteCreatedAtString: "3 weeks ago",
    ageInDays: 28,
  },
  {
    title: "Senior Software Engineer",
    link: "https://lt.linkedin.com/jobs/view/senior-software-engineer-at-nasdaq-3831358504?position=27&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=7W8U0Xgv9BHizF9Iwp6SXw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Nasdaq",
    websiteCreatedAtDateTime: "2024-03-08",
    websiteCreatedAtString: "1 month ago",
    ageInDays: 39,
  },
  {
    title: "WooCommerce Senior Developer",
    link: "https://lt.linkedin.com/jobs/view/woocommerce-senior-developer-at-synergy-effect-3890798301?position=28&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=%2Fq0kH8ssl1bZPNbeZamq3A%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Synergy Effect",
    websiteCreatedAtDateTime: "2024-04-10",
    websiteCreatedAtString: "5 days ago",
    ageInDays: 6,
  },
  {
    title: "Lead DevOps Engineer",
    link: "https://lt.linkedin.com/jobs/view/lead-devops-engineer-at-telia-3835921475?position=29&pageNum=0&refId=l7JyYMClDRqUAH3WwTM4oQ%3D%3D&trackingId=Y2uJcxN0H2kDuO%2BKEpwojw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Telia",
    websiteCreatedAtDateTime: "2024-03-20",
    websiteCreatedAtString: "3 weeks ago",
    ageInDays: 27,
  },
];
