CREATE TABLE job (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    title VARCHAR(255) NOT NULL,
    link VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    age INT NOT NULL,
    promoted BOOLEAN NOT NULL DEFAULT 0,
    easyApply BOOLEAN NOT NULL DEFAULT 0,
    jobWebsite VARCHAR(255) NOT NULL,
    applied BOOLEAN NOT NULL DEFAULT 0,
    websiteCreatedAt VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    userId INT,
    FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE,
    UNIQUE (link)
)