CREATE TABLE job_type (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    full_time BOOLEAN NOT NULL DEFAULT 0,
    part_time BOOLEAN NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    settings_id INT,
    FOREIGN KEY (settings_id) REFERENCES settings(id) ON DELETE CASCADE,
    UNIQUE(settings_id)
)