CREATE TABLE settings (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    appliedFilter BOOLEAN NOT NULL DEFAULT 0,
    blacklistedFilter BOOLEAN NOT NULL DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    userId INT,
    FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE,
    UNIQUE(userId)
)