CREATE TABLE settings (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    applied_filter BOOLEAN NOT NULL DEFAULT 0,
    blacklisted_filter BOOLEAN NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
    UNIQUE(user_id)
)