CREATE TABLE post (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    title VARCHAR(255) NOT NULL,
    link VARCHAR(500) NOT NULL,
    ageInDays VARCHAR(255) NOT NULL,
    companyName VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    applied BOOLEAN NOT NULL DEFAULT 0,
    websiteCreatedAtDateTime VARCHAR(255) NOT NULL,
    websiteCreatedAtString VARCHAR(255) NOT NULL,
    keywords VARCHAR(255) NOT NULL,
    blacklisted BOOLEAN NOT NULL DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    userId INT,
    FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE,
    UNIQUE (link)
)