export const BLACKLISTED_KEYWORDS = ["senior", "lead", "php"];
export const MAX_AGE = 20;

export const TABLE_LIST = ["user", "job", "blacklist", "settings"];

export const CLEAN_DATA = [
  {
    title: "Frontend Developer",
    link: "https://lt.linkedin.com/jobs/view/frontend-developer-at-macaw-lithuania-3885133519?position=2&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=tHfjSujJt1deNl0504totw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilniaus, Lithuania",
    companyName: "Macaw Lithuania",
    websiteCreatedAtDateTime: "2024-04-08",
    websiteCreatedAtString: "1 week ago",
    ageInDays: 10,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Full-Stack Developer",
    link: "https://lt.linkedin.com/jobs/view/full-stack-developer-at-w3forge-3893978734?position=7&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=h9s%2FmuFndNYj8YTkqHe7Sg%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "W3Forge",
    websiteCreatedAtDateTime: "2024-04-11",
    websiteCreatedAtString: "6 days ago",
    ageInDays: 7,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "FuturePros Programme: IT and Software Engineering Track",
    link: "https://lt.linkedin.com/jobs/view/futurepros-programme-it-and-software-engineering-track-at-danske-bank-3895354921?position=8&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=yX1OY%2BrZoqsjhF5vgvUHdw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Danske Bank",
    websiteCreatedAtDateTime: "2024-04-17",
    websiteCreatedAtString: "5 hours ago",
    ageInDays: 1,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "DevOps Engineer",
    link: "https://lt.linkedin.com/jobs/view/devops-engineer-at-telia-3892340439?position=24&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=m5YPbvbpxedVPJKJPFmJwQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Telia",
    websiteCreatedAtDateTime: "2024-04-12",
    websiteCreatedAtString: "5 days ago",
    ageInDays: 6,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "DevOps Engineer",
    link: "https://lt.linkedin.com/jobs/view/devops-engineer-at-telia-3890828716?position=25&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=PP12IKymJABMZf5rQbC8Sg%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Telia",
    websiteCreatedAtDateTime: "2024-04-11",
    websiteCreatedAtString: "6 days ago",
    ageInDays: 7,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
];

export const UNFILTERED_DATA = [
  {
    title: "Front-End Developer (Web team)",
    link: "https://lt.linkedin.com/jobs/view/front-end-developer-web-team-at-surfshark-3815235850?position=1&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=1yQjmlRaoI%2FYKNIt2v570w%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Surfshark",
    websiteCreatedAtDateTime: "2024-02-01",
    websiteCreatedAtString: "2 months ago",
    ageInDays: 77,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Frontend Developer",
    link: "https://lt.linkedin.com/jobs/view/frontend-developer-at-macaw-lithuania-3885133519?position=2&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=tHfjSujJt1deNl0504totw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilniaus, Lithuania",
    companyName: "Macaw Lithuania",
    websiteCreatedAtDateTime: "2024-04-08",
    websiteCreatedAtString: "1 week ago",
    ageInDays: 10,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Fullstack Developer",
    link: "https://lt.linkedin.com/jobs/view/fullstack-developer-at-obdeleven-3871939306?position=3&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=%2ByMgfzBh1lIXr5D8AhhymQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Kaunas, Kauno, Lithuania",
    companyName: "OBDeleven",
    websiteCreatedAtDateTime: "2024-03-26",
    websiteCreatedAtString: "3 weeks ago",
    ageInDays: 23,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Mid-Senior Front-End Engineer (WEB team)",
    link: "https://lt.linkedin.com/jobs/view/mid-senior-front-end-engineer-web-team-at-nord-security-3880681353?position=4&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=bmxHCDYdhKnid3xkctDuug%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Nord Security",
    websiteCreatedAtDateTime: "2024-04-03",
    websiteCreatedAtString: "1 week ago",
    ageInDays: 15,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Mid-Senior Front-end Engineer",
    link: "https://lt.linkedin.com/jobs/view/mid-senior-front-end-engineer-at-nord-security-3868482388?position=5&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=AszcDU9sl2SR%2BxzXRz3gFw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Nord Security",
    websiteCreatedAtDateTime: "2024-03-26",
    websiteCreatedAtString: "3 weeks ago",
    ageInDays: 23,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Mid-Senior Front-End Engineer (WEB team)",
    link: "https://lt.linkedin.com/jobs/view/mid-senior-front-end-engineer-web-team-at-nord-security-3880679411?position=6&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=pglKENkqSTBahioZOxwjtQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Kaunas, Kauno, Lithuania",
    companyName: "Nord Security",
    websiteCreatedAtDateTime: "2024-04-03",
    websiteCreatedAtString: "1 week ago",
    ageInDays: 15,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Full-Stack Developer",
    link: "https://lt.linkedin.com/jobs/view/full-stack-developer-at-w3forge-3893978734?position=7&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=h9s%2FmuFndNYj8YTkqHe7Sg%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "W3Forge",
    websiteCreatedAtDateTime: "2024-04-11",
    websiteCreatedAtString: "6 days ago",
    ageInDays: 7,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "FuturePros Programme: IT and Software Engineering Track",
    link: "https://lt.linkedin.com/jobs/view/futurepros-programme-it-and-software-engineering-track-at-danske-bank-3895354921?position=8&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=yX1OY%2BrZoqsjhF5vgvUHdw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Danske Bank",
    websiteCreatedAtDateTime: "2024-04-17",
    websiteCreatedAtString: "5 hours ago",
    ageInDays: 1,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Senior Frontend Developer",
    link: "https://lt.linkedin.com/jobs/view/senior-frontend-developer-at-coingate-3874348577?position=9&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=dVa0m3QS%2FXUovBbwmxdfYA%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "CoinGate",
    websiteCreatedAtDateTime: "2024-03-29",
    websiteCreatedAtString: "2 weeks ago",
    ageInDays: 20,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Senior Software Engineer  (Remote or Hybrid)",
    link: "https://lt.linkedin.com/jobs/view/senior-software-engineer-remote-or-hybrid-at-hokodo-3879304038?position=10&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=UZ9xXYJ4re7SmFoj3y6WUA%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Hokodo",
    websiteCreatedAtDateTime: "2024-04-02",
    websiteCreatedAtString: "2 weeks ago",
    ageInDays: 16,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "FACT Team Offshore Developers",
    link: "https://lt.linkedin.com/jobs/view/fact-team-offshore-developers-at-higher-frog-limited-3890810902?position=11&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=QrKwYn6PPHLhqvQelTpXIg%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Lithuania",
    companyName: "Higher Frog Limited",
    websiteCreatedAtDateTime: "2024-03-17",
    websiteCreatedAtString: "1 month ago",
    ageInDays: 32,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Product Engineer",
    link: "https://lt.linkedin.com/jobs/view/product-engineer-at-inbank-3874829057?position=12&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=gERTQ7uFV0lMMi1EXmzQiQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Inbank",
    websiteCreatedAtDateTime: "2024-03-28",
    websiteCreatedAtString: "2 weeks ago",
    ageInDays: 21,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Javascript Developer",
    link: "https://lt.linkedin.com/jobs/view/javascript-developer-at-ubiquiti-inc-3739270393?position=13&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=4uV6tA5rV9ml97tXhd70zg%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Kaunas, Kauno, Lithuania",
    companyName: "Ubiquiti Inc.",
    websiteCreatedAtDateTime: "2024-03-14",
    websiteCreatedAtString: "1 month ago",
    ageInDays: 35,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "FACT Team Offshore Developers",
    link: "https://lt.linkedin.com/jobs/view/fact-team-offshore-developers-at-higher-frog-limited-3890814620?position=14&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=SRwPBKGcHIM%2BhmtdgeuJpA%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Lithuania",
    companyName: "Higher Frog Limited",
    websiteCreatedAtDateTime: "2024-03-17",
    websiteCreatedAtString: "1 month ago",
    ageInDays: 32,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "FACT Team Offshore Developers",
    link: "https://lt.linkedin.com/jobs/view/fact-team-offshore-developers-at-higher-frog-limited-3890811926?position=15&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=bc%2Brqo7Qtrdl8iK4ksvuzA%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Lithuania",
    companyName: "Higher Frog Limited",
    websiteCreatedAtDateTime: "2024-03-17",
    websiteCreatedAtString: "1 month ago",
    ageInDays: 32,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "(Senior) Data Scientists - based in Luxembourg",
    link: "https://lt.linkedin.com/jobs/view/senior-data-scientists-based-in-luxembourg-at-european-investment-bank-eib-3860351600?position=16&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=oZGDSSBlS6zyaysISk%2Bt%2Bw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilniaus rajonas, Vilniaus, Lithuania",
    companyName: "European Investment Bank (EIB)",
    websiteCreatedAtDateTime: "2024-03-19",
    websiteCreatedAtString: "4 weeks ago",
    ageInDays: 30,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Middle Full-Stack Developer",
    link: "https://lt.linkedin.com/jobs/view/middle-full-stack-developer-at-exadel-3822888600?position=17&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=wnK0jUpKvaStUtkKynYCNQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Lithuania",
    companyName: "Exadel",
    websiteCreatedAtDateTime: "2024-02-05",
    websiteCreatedAtString: "2 months ago",
    ageInDays: 73,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "FULL STACK .NET DEVELOPER",
    link: "https://lt.linkedin.com/jobs/view/full-stack-net-developer-at-aida-projektai-3862859839?position=18&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=l3EbVee4uLXNjvKs96GcAQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "AIDA projektai",
    websiteCreatedAtDateTime: "2024-03-19",
    websiteCreatedAtString: "4 weeks ago",
    ageInDays: 30,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Senior Software Engineer",
    link: "https://lt.linkedin.com/jobs/view/senior-software-engineer-at-unmanned-defense-systems-3899652533?position=19&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=b10D1fC1OY0nHMBmTpwWDQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Unmanned Defense Systems",
    websiteCreatedAtDateTime: "2024-04-15",
    websiteCreatedAtString: "2 days ago",
    ageInDays: 3,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Senior Full-Stack Developer",
    link: "https://lt.linkedin.com/jobs/view/senior-full-stack-developer-at-exadel-3851272608?position=20&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=7a2DBqesUl6Qm59kdCRytw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Lithuania",
    companyName: "Exadel",
    websiteCreatedAtDateTime: "2024-03-11",
    websiteCreatedAtString: "1 month ago",
    ageInDays: 38,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Senior Frontend Web Engineer",
    link: "https://lt.linkedin.com/jobs/view/senior-frontend-web-engineer-at-flo-health-inc-3876782564?position=21&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=JOtUlZu28zlBWCL0vnvq5g%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Flo Health Inc.",
    websiteCreatedAtDateTime: "2024-03-29",
    websiteCreatedAtString: "2 weeks ago",
    ageInDays: 20,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Senior Web Developer - Workplace Engineering",
    link: "https://lt.linkedin.com/jobs/view/senior-web-developer-workplace-engineering-at-canonical-3673076613?position=22&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=miSV8AMFS4SXtLuv1MBK8A%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Canonical",
    websiteCreatedAtDateTime: "2023-06-27",
    websiteCreatedAtString: "9 months ago",
    ageInDays: 296,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Middle/Senior React Front-End Developer (On-Site in Vilnius)",
    link: "https://lt.linkedin.com/jobs/view/middle-senior-react-front-end-developer-on-site-in-vilnius-at-it-gateway-lt-3871221424?position=23&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=ZJRVgzYPLq8e0zwTNBAZjQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "IT Gateway LT",
    websiteCreatedAtDateTime: "2024-03-28",
    websiteCreatedAtString: "2 weeks ago",
    ageInDays: 21,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "DevOps Engineer",
    link: "https://lt.linkedin.com/jobs/view/devops-engineer-at-telia-3892340439?position=24&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=m5YPbvbpxedVPJKJPFmJwQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Telia",
    websiteCreatedAtDateTime: "2024-04-12",
    websiteCreatedAtString: "5 days ago",
    ageInDays: 6,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "DevOps Engineer",
    link: "https://lt.linkedin.com/jobs/view/devops-engineer-at-telia-3890828716?position=25&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=PP12IKymJABMZf5rQbC8Sg%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Telia",
    websiteCreatedAtDateTime: "2024-04-11",
    websiteCreatedAtString: "6 days ago",
    ageInDays: 7,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Senior Software Engineer - iTwin Applications",
    link: "https://lt.linkedin.com/jobs/view/senior-software-engineer-itwin-applications-at-bentley-systems-3872070029?position=26&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=EIEfMnoc2IYIJVA4jvCeEw%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Bentley Systems",
    websiteCreatedAtDateTime: "2024-03-27",
    websiteCreatedAtString: "2 weeks ago",
    ageInDays: 22,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Atlassian Jira & Confluence DevOps Engineer",
    link: "https://lt.linkedin.com/jobs/view/atlassian-jira-confluence-devops-engineer-at-telia-3831257748?position=27&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=dcgUt8B42TmkuZioDRDSPQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Telia",
    websiteCreatedAtDateTime: "2024-03-14",
    websiteCreatedAtString: "1 month ago",
    ageInDays: 35,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Senior FrontEnd Developer",
    link: "https://lt.linkedin.com/jobs/view/senior-frontend-developer-at-zedge-3872032670?position=28&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=O8aE3iIiP8yu%2B80Inv%2BxGQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "ZEDGE",
    websiteCreatedAtDateTime: "2024-04-02",
    websiteCreatedAtString: "2 weeks ago",
    ageInDays: 16,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Full-stack Engineer (AWS, Java)",
    link: "https://lt.linkedin.com/jobs/view/full-stack-engineer-aws-java-at-telia-3860315301?position=29&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=BHDnH6SqKxiVQ1r%2BohDvyQ%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Telia",
    websiteCreatedAtDateTime: "2024-03-19",
    websiteCreatedAtString: "4 weeks ago",
    ageInDays: 30,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Senior Software Engineer",
    link: "https://lt.linkedin.com/jobs/view/senior-software-engineer-at-nasdaq-3831358504?position=30&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=EeRch7HVv4GF7zeanGEOog%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Nasdaq",
    websiteCreatedAtDateTime: "2024-03-08",
    websiteCreatedAtString: "1 month ago",
    ageInDays: 41,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
  {
    title: "Lead DevOps Engineer",
    link: "https://lt.linkedin.com/jobs/view/lead-devops-engineer-at-telia-3835921475?position=31&pageNum=0&refId=bMizU3n41WVnbxnsliPlag%3D%3D&trackingId=%2Bg7Y9l0Xb3FaosAQFrQF9A%3D%3D&trk=public_jobs_jserp-result_search-card",
    location: "Vilnius, Vilniaus, Lithuania",
    companyName: "Telia",
    websiteCreatedAtDateTime: "2024-03-20",
    websiteCreatedAtString: "4 weeks ago",
    ageInDays: 29,
    keywords: "next js",
    applied: false,
    blacklisted: false,
  },
];
